# fly.toml app configuration file generated for aliyeysides on 2023-11-25T20:20:49-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "aliyeysides"
primary_region = "ewr"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[build.args]
  BP_KEEP_FILES = "assets/*:resources/*"
