// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func WorkPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<body><div class=\"container\"><h1>Ali Yeysideş</h1><p>sample of my work</p><div class=\"content\"><h2>open source & personal</h2><a href=\"https://github.com/aliyeysides/snake-go\" target=\"_blank\">Snake written in Go + Raylib</a> <a href=\"https://github.com/ccurme/yolopandas\" target=\"_blank\">yolopandas</a> <a href=\"https://github.com/run-llama/llama_index\" target=\"_blank\">llama index</a> <a href=\"https://github.com/aliyeysides/prisma-gpt\" target=\"_blank\">prisma-gpt</a> <a href=\"https://github.com/aliyeysides/openai-quickstart-ruby\" target=\"_blank\">openai-quickstart-ruby</a> <a href=\"https://github.com/aliyeysides/bar\" target=\"_blank\">B.A.R (Burn After Reading): open source paste bin</a> <a href=\"https://github.com/aliyeysides/click_call\" target=\"_blank\">click call: make phone calls from the browser</a> <a href=\"https://github.com/aliyeysides/Rosie\" target=\"_blank\">C# discord bot</a> <a href=\"https://github.com/aliyeysides/PinPoint\" target=\"_blank\">pinpoint: annotate youtube videos</a><h2>professional</h2><a href=\"https://brikmate.com\" target=\"_blank\">brikmate</a> <a href=\"https://investor.vanguard.com/advice/personal-financial-advice-options\" target=\"_blank\">vanguard PAS</a> <a href=\"https://localizejs.com/products/documents\" target=\"_blank\">localizejs documents</a></div></div></body>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = layout().Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
